# Generated by Django 3.1.6 on 2021-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cia',
            name='cia',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='type_goal',
            name='type_goal',
            field=models.CharField(default='', max_length=30),
        ),
    ]
