# Generated by Django 3.1.6 on 2021-02-10 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cia', models.CharField(default='', editable=False, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='', editable=False, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Type_goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_goal', models.CharField(default='', editable=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('initial_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('cia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.cia')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.sector')),
                ('type_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.type_goal')),
            ],
        ),
    ]
